### ISSUE TITLE
想询问一下几个超参具体的含义

### ISSUE THREAD

**Issue by callmeYe** [Edward-Sun/SLM#1]
我使用你们构建的模型训练时，不是很明白WINDOW_SIZE、LAMBDA、hrate三个参数具体的含义和如何调参，不知道您可不可以解释一下，感谢。

**Comment by Edward-Sun** [comment]
WINDOW_SIZE是在句子的前后补充</s>，这个模型没有用到这个信息，我会把这个clean掉的。
LAMBDA是指我们论文里半监督学习时 supervised 和 unsupervised 部分的比例。
hrate 本来应该是 encoder 的 hidden state 到 decoder 的 hidden state 时候的 dropout rate，现在一看发现后来改成 drop_h = hrate * h 了，这样子也没有意义了，我也会把这个clean掉。。。

不好意思，之前没工夫clean代码然后后来忘了。。。我这星期会clean一下代码然后加点注释。。。

调参的话如果只是纯unsupervised，就只要调 batch size, learning rate 和 max segment length 就可以了

**Comment by callmeYe** [comment]
多谢
