### ISSUE TITLE
Help:  Could you please add some step-by-step descriptions for reproducing. 

### ISSUE THREAD

**Issue by moonblue333** [Edward-Sun/SLM#2]
And the data format.

**Comment by moonblue333** [comment]
And the data format.

**Comment by moonblue333** [comment]
BATCH_SIZE = 512定义了两次
文档说明中BATCH2，如果是BATCH_SIZE2，建议就描述为BATCH_SIZE2,否则还以为有另外一个参数。

**Comment by moonblue333** [comment]
代码感觉可以稍微整理一下，比如下面这种语句，就比较困惑。 cell_h_start, cell_c_start看起来是没用的。
    h, c = cell_h_start, cell_c_start
    h, c = self.LSTMCell(self.dropout(y_start), (h, c))

**Comment by moonblue333** [comment]
drop_h = self.hrate * h    当hrate为一个浮点值的时候，并不是一个drop的作用，是把hidden-state的scale小而已。 但每次都滑动的时候，都乘以一个靠近0的数，相当于在不断遗忘/弱化前面的词的影响。感觉应该搞给和max-seg结合的遗忘策略（算法更复杂一些:  在max_seg内不要忘成0），这样更利于在max-seg范围内的词的高度关联。

**Comment by Edward-Sun** [comment]
过年的时候实验室服务器坏了。。。。这周就重写（哭

**Comment by moonblue333** [comment]
我已经在重写了，就一个200行的文件，全部搞定，我修改好了，提交给你。 （最近因为需要，也在研究看无监督的分词，论文很少，靠谱的更少，你这个版本还是很不错，加油，牛牛。）
1.  我们是不是可以综合一下其他人的无监督的思想。
2.  尝试一下transformer，是不是比RNN效果更好？或者至少用过Bi-LSTM试试？（你本质还是在LSTM之上，得到带有上下文信息的h）
3.  无监督的“无”本身如何做到，是不是可以用一些其他的做法，来提升效率。 是不是只有现在这样贪婪组合（for j_start, j_len, j_end in schedule:）比较概率？

**Comment by moonblue333** [comment]
pku dataset最大长度，超过1024了，感觉不截断，比较浪费内存/显存。 我用TitanXP，batch-size还不能到32。

**Comment by moonblue333** [comment]
schedule中，主要组合的是单个字符滑动下的max_seg，需不需要组合1~max_seg？
意思是：
比如： 我爱祖国， max_seg=2
现在的组合： 我爱，爱组，祖国，国
是否需要：我，我爱，爱，爱祖，组，祖国，国
还是说for j in range(j_start, j_end):  这里出来的类似的概率，而且计算量少一些？

**Comment by moonblue333** [comment]
max_seg，3是不是够了？
分词，是不是上下文关系可以关注的比较短一些，hrate设置的比较小遗忘的快。

**Comment by Edward-Sun** [comment]
你好，我已重新把代码写了一遍，过几天会把pretrained的模型放出来
