### ISSUE TITLE
How could <eos> be generated under unsupervised condition?

### ISSUE THREAD

**Issue by empty-id** [Edward-Sun/SLM#3]
There is no <eos> in training data.

**Comment by Edward-Sun** [comment]
Hi, thank you for your interest in our work. The <eos> is generated at the end of each segment. For example, for a sentence

我们先来看什么是SLM

given a segmentation, 我们 先来 看 什么 是 SLM, the tokens generated by the segment decoder would be

我们<eos>, 先来<eos>, 看<eos>, 什么<eos>, 是<eos>, SLM<eos>

As this is unsupervised word segmentation, our model uses dynamic programming to enumerate all possible combinations of segmentation, sum them up to get the likelihood of the sentence, and maximize this likelihood.
